name: Studio1designhaus
favicon: null
layout_spectrum: 0.2222926220856607
typography_spectrum: 0.9129425585269928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.24944251449778676
  lightness: 0.5718727356288582
  saturation: 0.8648337223567069
  rhythmicContrast: 0.9049799179192632
purpose: []
